#!/bin/bash -e

# Copyright (c) 2014 The CoreOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# We want to grab the GROUP variable
[ -e /usr/share/coreos/update.conf ] && source /usr/share/coreos/update.conf
[ -e /etc/coreos/update.conf ] && source /etc/coreos/update.conf

source /usr/lib/os-release

mkdir -p /run/coreos
echo -e "\e[${ANSI_COLOR}m${NAME}\e[39m ${GROUP} (${VERSION})" > /run/coreos/motd

for file in /etc/motd.d/*.conf; do
	if [ -f "$file" ]; then
		if [ -x "$file" ]; then
			"$file" || true
		else
			cat "$file"
		fi
	fi
done 2>/dev/null >> /run/coreos/motd
